
.TH beings2 1 "June 17, 2026"
.SH NAME
beings2 \- Text-mode battle simulator.
.PP
.SH SYNOPSIS
beings2
.PP
.SH DESCRIPTION
Successor to beings. Instead of a pure simple AI simulator as the predecessor, this program is also a two-team battle simulator. Each being has individual decision making depending on surrounding and other beings. In attack mode, every being will try to attack whenever a being in the opposite team is sighted.
.PP
.SH How-to
Simulation modes to switch between:
.br
F - Freeroam (No attacks are performed.)
.br
R - Regroup (Both teams withdraw to opposite sides of the field.)
.br
A - Attack (Fighting mode. All beings attack when an opposite team being is sighted.)
.br
"+" and "-" to change simulation speed.
.PP
.SH BUGS
No known.
.PP
.SH AUTHOR
schnitz (https://github.com/schnitz81)
